name: Vprofile CI/CD Workflow
on: 
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron: '10 14 * * 1-5'  # At 14:10 on every day-of-week from Monday through Friday.

permissions:
  contents: read

jobs:
  Build:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Maven Build
      run: mvn clean install

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: vprofile-app
        path: target/*.war

    - name: Notify if Build Fails
      if: failure()
      run: echo "Build failed! Please check the logs."



  Testing:
   needs: Build
   runs-on: ubuntu-latest
   steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Maven Test
      run: mvn test

    - name: Checkstyle
      run: mvn checkstyle:checkstyle

    - name: Run tests on other branches
      if: github.ref == 'refs/heads/main'
      run: echo "Skipping tests on main branch"

  Security-Scan:
   needs: Build
   runs-on: ubuntu-latest
   steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run Security Scan
      uses: aquasecurity/trivy-action@v0.10.3
      with:
        scan-type: 'fs'
        scan-ref: .
        format: json
        exit-code: 
        vuln-type: 'os,library'
        output: 'trivy-report.json'

    - name: Upload Trivy Scan results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: trivy-scan-results
        path: trivy-report.json
    


