name: Vprofile CI/CD Workflow
on: 
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron: '10 14 * * 1-5'  # At 14:10 on every day-of-week from Monday through Friday.

env:
  ECR_REPOSITORY: vprofile-appimage

permissions:
  contents: read

jobs:
  Build:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Maven Build
      run: mvn clean install

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: vprofile-app
        path: target/*.war

    - name: Notify if Build Fails
      if: failure()
      run: echo "Build failed! Please check the logs."



  Testing:
   needs: Build
   runs-on: ubuntu-latest
   steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Maven Test
      run: mvn test

    - name: Checkstyle
      run: mvn checkstyle:checkstyle

    - name: Run tests on other branches
      if: github.ref == 'refs/heads/main'
      run: echo "Skipping tests on main branch"

  Security-Scan:
   needs: Build
   runs-on: ubuntu-latest
   steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run Security Scan
      uses: aquasecurity/trivy-action@0.33.1
      with:
        scan-type: 'fs'
        scan-ref: .
        format: json
        exit-code: 
        vuln-type: 'os,library'
        output: 'trivy-report.json'

    - name: Upload Trivy Scan results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: trivy-scan-results
        path: trivy-report.json

  BUILD_AND_PUBLISH:
      name: BUILD_AND_PUBLISH
      needs: Testing
      runs-on: ubuntu-latest
      environment: production
      needs: [Build, Testing, Security-Scan]
      if: github.ref == 'refs/heads/main'
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ vars.AWS_REGION }}
      
        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1

        - name: Build, tag, and push image to Amazon ECR
          id: build-image
          env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            IMAGE_TAG: ${{ github.sha }}
          run: |
            docker build -f Docker-files/app/multistage/Dockerfile/ -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
            echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

        